version: '3.6'
services:
  php:
    image: 'chialab/php-dev:7.3-apache'
    volumes:
      - '.:/var/www/html:cached'
      - './000-default.conf:/etc/apache2/sites-available/000-default.conf:cached'
    depends_on:
      - database
      - mailhog
  database:
    image: 'mariadb'
    environment:
      - MYSQL_ROOT_PASSWORD=root
  adminer:
    image: 'adminer'
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DESIGN=brade
  mailhog:
    image: 'mailhog/mailhog'
    ports:
      - '8025:8025'
      - '1025:1025'